### ISSUE TITLE
Add a column

### ISSUE THREAD

**Issue by myoungerman** [VerumEmanio/FlowchartMaker#2]
F12:G15 (the test) are the cells to append.

**Comment by VerumEmanio** [comment]
F12:G15 (the test) are the cells to append.

**Comment by myoungerman** [comment]
#5 enables the user to add one column. I still need to:
- [x] allow the user to add additional columns. This will require a formula like "if this is the first time the user adds a column, use L17 as the range, otherwise the range is the previous letter value + 3 and still row 17. For example, O17.
- [x] modify or add arrows as the user adds additional columns.

I can probably use a success handler to return a number that represents the number of columns the user has added.

**Comment by myoungerman** [comment]
I spent a lot of time yesterday writing unnecessary code, because there was a simpler solution. I've implemented the simpler solution now. I still need to address adding or modifying arrows.
