### ISSUE TITLE
Add a test to the column

### ISSUE THREAD

**Issue by myoungerman** [VerumEmanio/FlowchartMaker#3]
F10:G15 on the second sheet are the cells to append to the current column.

**Comment by VerumEmanio** [comment]
#5 enables the user to add one column. I still need to:
- [ ] allow the user to add additional columns. This will require a formula.
- [ ] modify or add arrows as the user adds additional columns.

**Comment by myoungerman** [comment]
To successfully append a test, I need:
- The number of the current column. The default column is column B.
-  The row the test should be added to, accounting for any previous tests that were added.

**Comment by myoungerman** [comment]
Resolved in #8. I wrote the code's output in Notepad as I worked through each iteration, solving a problem I encountered in just one line of code!
